# Generated by Django 4.0.4 on 2023-10-12 15:05

import bhtom2.bhtom_observatory.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Observatory name')),
                ('lon', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(-180.0, message='longitude must be greater than -180.'), django.core.validators.MaxValueValidator(180.0, message='longitude must be less than 180.')], verbose_name='Longitude (West is positive) [deg]')),
                ('lat', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(-180.0, message='latitude must be greater than -90.'), django.core.validators.MaxValueValidator(180.0, message='latitude must be less than 90.')], verbose_name='Latitude (North is positive) [deg]')),
                ('calibration_flg', models.BooleanField(db_index=True, default='False', verbose_name='Only instrumental photometry file')),
                ('prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('example_file', models.FileField(blank=True, null=True, upload_to=bhtom2.bhtom_observatory.models.example_file_path, verbose_name='Sample fits')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments (e.g. hyperlink to the observatory website, camera specifications, telescope info)')),
                ('active_flg', models.BooleanField(db_index=True, default='False')),
                ('altitude', models.FloatField(default=0.0, null=True, verbose_name='Altitude [m]')),
                ('gain', models.FloatField(default=2, null=True, verbose_name='Gain [e/ADU]')),
                ('readout_noise', models.FloatField(default=2, null=True, verbose_name='Readout Noise [e]')),
                ('binning', models.IntegerField(default=1, null=True)),
                ('saturation_level', models.FloatField(default=63000, null=True, verbose_name='Saturation Level [ADU]')),
                ('pixel_scale', models.FloatField(default=0.8, null=True, verbose_name='Pixel Scale [arcseconds/pixel]')),
                ('readout_speed', models.FloatField(default=9999.0, null=True, verbose_name='Readout Speed [microseconds/pixel]')),
                ('pixel_size', models.FloatField(default=13.5, null=True, verbose_name='Pixel size [micrometers]')),
                ('approx_lim_mag', models.FloatField(default=18.0, null=True, verbose_name='Approximate limit magnitude [mag]')),
                ('filters', models.CharField(blank=True, default='V,R,I', max_length=100, null=True, verbose_name='Filters (comma-separated list, as they are visible in FITS)')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'observatories',
                'unique_together': {('name', 'lon', 'lat')},
            },
        ),
        migrations.CreateModel(
            name='ObservatoryMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_flg', models.BooleanField(default='True')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments (e.g. hyperlink to the observatory website, camera specifications, telescope info)')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('number_of_uploaded_file', models.IntegerField(default=0)),
                ('last_file_process', models.DateTimeField(blank=True, null=True)),
                ('observatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_observatory.observatory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'observatory matrix',
                'unique_together': {('user', 'observatory')},
            },
        ),
    ]
