# Generated by Django 4.0.4 on 2023-10-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_observatory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observatorymatrix',
            name='file_size',
            field=models.FloatField(default=0),
        ),
    ]
