# Generated by Django 4.0.4 on 2023-07-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_observatory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observatory',
            options={'verbose_name_plural': 'observatories'},
        ),
    ]
