# Generated by Django 4.0.4 on 2023-08-04 13:13

import bhtom2.bhtom_observatory.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bhtom_observatory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observatorymatrix',
            options={'verbose_name_plural': 'observatory matrix'},
        ),
        migrations.RenameField(
            model_name='observatorymatrix',
            old_name='isActive',
            new_name='active_flg',
        ),
        migrations.RenameField(
            model_name='observatorymatrix',
            old_name='observatory_id',
            new_name='observatory',
        ),
        migrations.RenameField(
            model_name='observatorymatrix',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='observatory',
            name='active_flg',
            field=models.BooleanField(db_index=True, default='False'),
        ),
        migrations.AddField(
            model_name='observatory',
            name='calibration_flg',
            field=models.BooleanField(db_index=True, default='False', verbose_name='Only instrumental photometry file'),
        ),
        migrations.AddField(
            model_name='observatorymatrix',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observatorymatrix',
            name='last_file_process',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observatorymatrix',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='observatorymatrix',
            name='number_of_uploaded_file',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='example_file',
            field=models.FileField(upload_to=bhtom2.bhtom_observatory.models.example_file_path, verbose_name='Sample fits'),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='lat',
            field=models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(-180.0, message='latitude must be greater than -90.'), django.core.validators.MaxValueValidator(180.0, message='latitude must be less than 90.')], verbose_name='Latitude (North is positive) [deg]'),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='lon',
            field=models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(-180.0, message='longitude must be greater than -180.'), django.core.validators.MaxValueValidator(180.0, message='longitude must be less than 180.')], verbose_name='Longitude (West is positive) [deg]'),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='observatory',
            unique_together={('name', 'lon', 'lat')},
        ),
        migrations.AlterUniqueTogether(
            name='observatorymatrix',
            unique_together={('user', 'observatory')},
        ),
        migrations.RemoveField(
            model_name='observatory',
            name='cpcsOnly',
        ),
        migrations.RemoveField(
            model_name='observatory',
            name='isActive',
        ),
    ]
