# Generated by Django 4.0.4 on 2025-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_observatory', '0002_alter_observatory_comment_alter_observatory_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='observatory',
            name='acknowledgements',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Acknowledgements'),
        ),
        migrations.AddField(
            model_name='observatory',
            name='authors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Authors'),
        ),
    ]
