"""
Django settings for your TOM project.

Originally generated by 'django-admin startproject' using Django 2.1.1.
Generated by ./manage.py bhtom_setup on July 15, 2021, 7:27 p.m.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import logging.config
import os
import sys
import tempfile

from dotenv import dotenv_values

from bhtom2.external_service.data_source_information import DataSource, TARGET_NAME_KEYS

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Environment variables
secret = dotenv_values(os.path.join(BASE_DIR, 'bhtom2/.bhtom.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jkg5zb*xutcc+93y!00$7z409yrh%6#i@f)+h!$lyr3vqo9c)e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [] + list(secret.get("ALLOWED_HOSTS", 'localhost').split(','))
SITE_ID = int(secret.get("SITE_ID", 1))

CPCS_BASE_URL = secret.get('CPCS_BASE_URL', None)
CPCS_DATA_ACCESS_HASHTAG = secret.get('CPCS_DATA_ACCESS_HASHTAG', None)

WSDB_USER = secret.get('WSDB_USER','')
WSDB_PASSWORD = secret.get('WSDB_PASSWORD','')
WSDB_HOST = secret.get('WSDB_HOST','')
WSDB_PORT = secret.get('WSDB_PORT','')

ADMIN_USERNAME = secret.get('ADMIN_USERNAME')
ADMIN_PASSWORD = secret.get('ADMIN_PASSWORD')
ADMIN_EMAIL = secret.get('ADMIN_EMAIL','')

PROPOSALS_API_KEYS={
'LCO':secret.get('LCO_API_KEY','')
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'guardian',
    'bhtom_base.bhtom_common.apps.TomCommonConfig',
    'django_comments',
    'bootstrap4',
    'crispy_forms',
    'rest_framework',
    'django_filters',
    'django_tables2',
    'django_gravatar',
    'bhtom_base.bhtom_targets.apps.TomTargetsConfig',
    'bhtom_base.bhtom_alerts.apps.TomAlertsConfig',
    'bhtom_base.bhtom_catalogs.apps.TomCatalogsConfig',
    'bhtom_base.bhtom_observations.apps.TomObservationsConfig',
    'bhtom_base.bhtom_dataproducts.apps.TomDataproductsConfig',
    'bhtom_custom_registration.bhtom_registration.apps.TomRegistrationConfig',
    'rest_framework.authtoken',
    'bhtom2.apps.BHTOM2Config'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bhtom_base.bhtom_common.middleware.Raise403Middleware',
    'bhtom_base.bhtom_common.middleware.ExternalServiceMiddleware',
    'bhtom_base.bhtom_common.middleware.AuthStrategyMiddleware',
    'bhtom_custom_registration.bhtom_registration.middleware.RedirectAuthenticatedUsersFromRegisterMiddleware',
]

ROOT_URLCONF = 'bhtom2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'bhtom2/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

WSGI_APPLICATION = 'bhtom2.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'NAME': secret.get("POSTGRES_DB_NAME", 'bhtom2'),
        'ENGINE': 'django.db.backends.postgresql',
        'USER': secret.get("POSTGRES_DB_USER", 'bhtom'),
        'PASSWORD': secret.get("POSTGRES_PASSWORD", ""),
        'HOST': secret.get('POSTGRES_HOST', 'localhost'),
        'PORT': secret.get('POSTGRES_PORT', 5432),
        'TEST': {
            'NAME': secret.get("POSTGRES_TEST_DB_NAME", 'test_bhtom2')
        }
    },
}

MIGRATION_MODULES = {
    'bhtom2': 'bhtom2.migrations'
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
    'guardian.backends.ObjectPermissionBackend',
)

TOM_REGISTRATION = {
    'REGISTRATION_AUTHENTICATION_BACKEND': 'django.contrib.auth.backends.AllowAllUsersModelBackend',
    'REGISTRATION_REDIRECT_PATTERN': 'home',
    'SEND_APPROVAL_EMAILS': True
}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = True

DATETIME_FORMAT = 'Y-m-d H:m:s'
DATE_FORMAT = 'Y-m-d'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '_static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'bhtom2/static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'data')
MEDIA_URL = '/data/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'graypy': {
            'level': 'INFO',
            'class': 'graypy.GELFTCPHandler',
            'host': secret.get('GRAYLOG_HOST', 'localhost'),
            'port': secret.get('GRAYLOG_PORT', 12201),
        },
        'console': {
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        '': {
            'handlers': ['graypy', 'console'],
            'level': 'DEBUG'
        }
    },
}

# Caching
# https://docs.djangoproject.com/en/dev/topics/cache/#filesystem-caching

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': tempfile.gettempdir()
    }
}

# TOM Specific configuration
TARGET_TYPE = 'SIDEREAL'


# Define the valid data product types for your TOM. Be careful when removing items, as previously valid types will no
# longer be valid, and may cause issues unless the offending records are modified.
DATA_PRODUCT_TYPES = {
    'photometry': ('photometry', 'Photometry'),
    'photometry_nondetection': ('photometry_nondetection', 'Photometry Non-Detections'),
    'fits_file': ('fits_file', 'FITS File'),
    'spectroscopy': ('spectroscopy', 'Spectroscopy'),
    'image_file': ('image_file', 'Image File')
}

DATA_PROCESSORS = {
    'photometry': 'bhtom_base.bhtom_dataproducts.processors.photometry_processor.PhotometryProcessor',
    'spectroscopy': 'bhtom_base.bhtom_dataproducts.processors.spectroscopy_processor.SpectroscopyProcessor',
}


TOM_ALERT_CLASSES = [
    'bhtom_base.bhtom_alerts.brokers.alerce.ALeRCEBroker',
    'bhtom_base.bhtom_alerts.brokers.lasair.LasairBroker',
    'bhtom_base.bhtom_alerts.brokers.mars.MARSBroker',
    'bhtom_base.bhtom_alerts.brokers.scimma.SCIMMABroker',
    'bhtom_base.bhtom_alerts.brokers.scout.ScoutBroker',
    'bhtom_base.bhtom_alerts.brokers.tns.TNSBroker',
    'bhtom_base.bhtom_alerts.brokers.fink.FinkBroker',
    'bhtom2.brokers.gaia_alerts.GaiaAlertsBroker',
    'bhtom2.brokers.aavso.AAVSOBroker',
    'bhtom2.brokers.ztf.ZTFBroker',
    'bhtom2.brokers.gaia.GaiaBroker',
    'bhtom2.brokers.sdss.SDSSBroker',
    'bhtom2.brokers.neowise.NEOWISEBroker',
    'bhtom2.brokers.catalina.CRTSBroker',
    'bhtom2.brokers.linear.LINEARBroker',
    'bhtom2.brokers.first.FIRSTBroker',
    'bhtom2.brokers.ps1.PS1Broker'
    # 'bhtom2.brokers.antares.ANTARESBroker',
]

BROKERS = {
    'TNS': {
        'api_key': ''
    }
}

TOM_HARVESTER_CLASSES = [
    'bhtom2.harvesters.gaia_alerts.GaiaAlertsHarvester',
    'bhtom2.harvesters.tns.TNSHarvester',
    'bhtom2.harvesters.antares.ANTARESHarvester',
    'bhtom_base.bhtom_catalogs.harvesters.simbad.SimbadHarvester',
    'bhtom_base.bhtom_catalogs.harvesters.ned.NEDHarvester',
    'bhtom_base.bhtom_catalogs.harvesters.jplhorizons.JPLHorizonsHarvester',
]

HARVESTERS = {
    'TNS': {
        'api_key': ''
    }
}

# Define extra target fields here. Types can be any of "number", "string", "boolean" or "datetime"
# See https://tomtoolkit.github.io/docs/target_fields for documentation on this feature
# For example:
# EXTRA_FIELDS = [
#     {'name': 'redshift', 'type': 'number'},
#     {'name': 'discoverer', 'type': 'string'}
#     {'name': 'eligible', 'type': 'boolean'},
#     {'name': 'dicovery_date', 'type': 'datetime'}
# ]
EXTRA_FIELDS = [
    {'name': 'classification', 'type': 'string'},
    {'name': 'priority', 'type': 'number'},
    {'name': 'discovery_date', 'type': 'datetime'},
    {'name': 'cadence', 'type': 'number'},
    {'name': 'sun_separation', 'type': 'number'},
    {'name': 'dont_update_me', 'type': 'boolean', 'hidden': True}]

CREATE_TARGET_HIDDEN_EXTRA_FIELDS = [
    'sun_separation', 'dont_update_me', 'discovery_date'
]

CREATE_TARGET_HIDDEN_FIELDS = [
    'pm_ra', 'pm_dec', 'galactic_lat', 'galactic_lng', 'distance', 'distance_err'#, 'groups'
]

def generate_name_tuple(data_source: DataSource) -> tuple:
    return data_source.name, f'{data_source.name} name'


SOURCE_CHOICES = [generate_name_tuple(ds) for ds in DataSource]

# Authentication strategy can either be LOCKED (required login for all views)
# or READ_ONLY (read only access to views)
AUTH_STRATEGY = 'READ_ONLY'

# Row-level data permissions restrict users from viewing certain objects unless they are a member of the group to which
# the object belongs. Setting this value to True will allow all `ObservationRecord`, `DataProduct`, and `ReducedDatum`
# objects to be seen by everyone. Setting it to False will allow users to specify which groups can access
# `ObservationRecord`, `DataProduct`, and `ReducedDatum` objects.
TARGET_PERMISSIONS_ONLY = True

# URLs that should be allowed access even with AUTH_STRATEGY = LOCKED
# for example: OPEN_URLS = ['/', '/about']
OPEN_URLS = []

HOOKS = {
    'target_post_save': 'bhtom2.hooks.target_post_save',
    'reduced_datum_pre_save': 'bhtom_base.bhtom_dataproducts.hooks.reduced_datum_pre_save',
    'observation_change_state': 'bhtom_base.bhtom_common.hooks.observation_change_state',
    'data_product_post_upload': 'bhtom_base.bhtom_dataproducts.hooks.data_product_post_upload',
    'data_product_post_save': 'bhtom_base.bhtom_dataproducts.hooks.data_product_post_save',
    'multiple_data_products_post_save': 'bhtom_base.bhtom_dataproducts.hooks.multiple_data_products_post_save',
}

AUTO_THUMBNAILS = False

THUMBNAIL_MAX_SIZE = (0, 0)

THUMBNAIL_DEFAULT_SIZE = (200, 200)

HINTS_ENABLED = False
HINT_LEVEL = 20

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
    ],
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100
}

try:
    from local_settings import *  # noqa
except ImportError:
    pass

GAIA_ALERTS_PATH: str = 'http://gsaweb.ast.cam.ac.uk'
AAVSO_API_PATH: str = 'https://www.aavso.org/vsx/index.php'
ZTF_DR_PATH: str = 'https://irsa.ipac.caltech.edu/cgi-bin/ZTF/nph_light_curves'

# Observatories possible to request data
FACILITIES = {
    'LCO': {
        'portal_url': 'https://observe.lco.global',
        'api_key': PROPOSALS_API_KEYS['LCO'],
    },
}

TOM_FACILITY_CLASSES = [
    'bhtom_base.bhtom_observations.facilities.lco.LCOFacility',
    'bhtom2.bhtom_observations.facilities.ostrowik.Ostrowik',
    'bhtom2.bhtom_observations.facilities.rem.REM',
    'bhtom2.bhtom_observations.facilities.moletai.Moletai',
    'bhtom2.bhtom_observations.facilities.bilakow.Bialkow'
]
