# Generated by Django 3.2.9 on 2021-11-25 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewReducedDatum',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(default='', max_length=100)),
                ('source_name', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('value', models.TextField()),
                ('dp_extra_data', models.TextField(blank=True, null=True)),
                ('observation_record_facility', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
    ]
