# Generated by Django 4.0.4 on 2022-10-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Observatory name')),
                ('longitude', models.FloatField(verbose_name='Longitude (West is positive) [deg]')),
                ('latitude', models.FloatField(verbose_name='Latitude (North is positive) [deg]')),
                ('altitude', models.FloatField(default=0.0, verbose_name='Altitude [m]')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments (e.g. hyperlink to the observatory website)')),
                ('verified', models.BooleanField(default='False')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default='True')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments (e.g. hyperlink to the observatory website, camera specifications, telescope info)')),
                ('matchDist', models.CharField(choices=[('0.5', '0.5 arcsec'), ('1', '1 arcsec'), ('2', '2 arcsec'), ('4', '4 arcsec'), ('6', '6 arcsec')], default='2', max_length=10, verbose_name='Matching radius')),
                ('gain', models.FloatField(default=2, verbose_name='Gain [e/ADU]')),
                ('readout_noise', models.FloatField(default=2, verbose_name='Readout Noise [e]')),
                ('binning', models.IntegerField(default=1)),
                ('saturation_level', models.FloatField(default=63000, verbose_name='Saturation Level [ADU]')),
                ('pixel_scale', models.FloatField(default=0.8, verbose_name='Pixel Scale [arcseconds/pixel]')),
                ('readout_speed', models.FloatField(default=9999.0, verbose_name='Readout Speed [microseconds/pixel]')),
                ('pixel_size', models.FloatField(default=13.5, verbose_name='Pixel size [micrometers]')),
                ('approx_lim_mag', models.FloatField(default=18.0, verbose_name='Approximate limit magnitude [mag]')),
                ('filters', models.CharField(blank=True, default='V,R,I', max_length=100, verbose_name='Filters (comma-separated list, as they are visible in FITS)')),
                ('obs_info_file', models.FileField(null=True, upload_to='uploads/obs_info', verbose_name='Obs Info')),
                ('sample_fits', models.FileField(upload_to='uploads/sample_fits', verbose_name='Sample FITS file')),
                ('observatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom2.observatory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
