\set pswrd `echo "$POSTGRES_PASSWORD"`

CREATE USER bhtom WITH PASSWORD :'bhtom2';
ALTER USER bhtom CREATEDB;

CREATE DATABASE bhtom2;
GRANT ALL PRIVILEGES ON DATABASE bhtom2 TO bhtom2;

CREATE DATABASE test_bhtom2;
GRANT ALL PRIVILEGES ON DATABASE test_bhtom2 TO bhtom2;