CREATE USER bhtom WITH PASSWORD :'pswrd';
ALTER USER bhtom CREATEDB;

CREATE DATABASE bhtom2;
GRANT ALL PRIVILEGES ON DATABASE bhtom2 TO bhtom;

CREATE DATABASE test_bhtom2;
GRANT ALL PRIVILEGES ON DATABASE test_bhtom2 TO bhtom;
