# Generated by Django 4.0.4 on 2023-07-12 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bhtom_dataproducts', '0024_alter_reduceddatum_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('survey', models.TextField(editable=False)),
                ('filters', models.TextField(editable=False)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='cpcsData',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('mjd', models.FloatField(blank=True, null=True)),
                ('expTime', models.FloatField(blank=True, null=True)),
                ('mag', models.FloatField(blank=True, null=True)),
                ('mag_error', models.FloatField(blank=True, null=True)),
                ('ra', models.FloatField(blank=True, null=True)),
                ('dec', models.FloatField(blank=True, null=True)),
                ('zeropoint', models.FloatField(blank=True, null=True)),
                ('outlier_fraction', models.FloatField(blank=True, null=True)),
                ('scatter', models.FloatField(blank=True, null=True)),
                ('npoints', models.IntegerField(blank=True, null=True)),
                ('processing_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('best_filter', models.CharField(blank=True, max_length=5, null=True)),
                ('match_distans', models.FloatField(default=0.5)),
                ('noPlot', models.BooleanField(default=True)),
                ('cpcsPlot', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('dataproduct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_dataproducts.dataproduct')),
                ('useCatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_calibration.catalogs')),
            ],
            options={
                'verbose_name': 'cpcs processing file',
                'verbose_name_plural': 'cpcsData',
            },
        ),
    ]
