# Generated by Django 4.0.4 on 2024-02-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bhtom_calibration', '0001_initial'),
        ('bhtom_dataproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration_data',
            name='dataproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_dataproducts.dataproduct'),
        ),
        migrations.AddField(
            model_name='calibration_data',
            name='use_catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bhtom_calibration.catalogs'),
        ),
    ]
