# Generated by Django 4.0.4 on 2024-06-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration_data',
            name='calibration_log',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='calibration_data',
            name='use_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bhtom_calibration.catalogs'),
        ),
    ]