# Generated by Django 4.0.4 on 2023-08-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration_data',
            name='exp_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
