name: Build and Push Docker Image to hub.astrolabs.pl

on:
  push:
    branches:
      - bhtom2-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: https://hub.astrolabs.pl
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Extract version from date
        id: version
        run: |
          VERSION=$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: docker build -f testdocker/Dockerfile -t https://hub.astrolabs.pl/bh-tom2/bh-tom2:${{ env.VERSION }} .

      - name: Tag Docker image as latest
        run: docker tag https://hub.astrolabs.pl/bh-tom2/bh-tom2:${{ env.VERSION }} https://hub.astrolabs.pl/bh-tom2/bh-tom2:latest

      - name: Push versioned Docker image
        run: docker push https://hub.astrolabs.pl/bh-tom2/bh-tom2:${{ env.VERSION }}

      - name: Push latest Docker image
        run: docker push https://hub.astrolabs.pl/bh-tom2/bh-tom2:latest
